### PR TITLE
tick version to 0.5.0

### LINKED ISSUE #8: Time.measure isn't affected by Timecop.scale in 0.4.1
In the sample below I expected duration to be roughly 100:

```crystal
require "timecop"

n = Time::Span.new

Timecop.scale 100 do
  # 1 wallclock second should measure as 100 seconds
  duration = Time.measure do
    sleep 1
  end

  pp duration
  # => 00:00:01.001259792
end
```

### PR DESCRIPTION
**Pull request by robacarp**
fixes #8 

The fix code is already in master, unreleased.

I chose to increment a minor version rather than a patch because the previous release didn't mock out monotonic, which means that #measure didn't work as it should. This is technically a bug-fix but it's entirely possible there are folks who have written code around the buggy nature.

### CODE REVIEW

**Comment by Sija** [comment]
image

this looks like a major BS...

**Review by Sija — APPROVED** [review]

**Comment by veelenga** [comment]
@Sija i removed the branch protection rule (signed commits)

**Comment by robacarp** [comment]
Travis seems broken. I ran the tests on my local against Crystal 1.6.1:

```
bartholemu-pink ~/R/c/timecop.cr> asdf shell crystal 1.6.2
~/R/c/timecop.cr> crystal spec
..............*..

Pending:
  Timecop .travel does not reduce precision

Finished in 1.76 seconds
17 examples, 0 failures, 0 errors, 1 pending

0.5.0-release 449d0be4 Nov-25 13:56:30 ∆t=3s 620ms 
```

**Comment by robacarp** [comment]
Thanks @Sija @veelenga

**Pull request merged**
