### PR TITLE
Fixed required Crystal version to support Crystal 1.0.0

### PR DESCRIPTION
**Pull request by igor-alexandrov**
Created new PR instead of https://github.com/crystal-community/timecop.cr/pull/6.

### CODE REVIEW

**Comment by igor-alexandrov** [comment]
Guys, what is the status of this?

**Comment by veelenga** [comment]
The change looks good to me, however, are we sure it fixes the original problem? In my understanding, it doesn't have any difference in terms of version resolution as a dependency for awscr-s3

**Review by veelenga — APPROVED** [review]

**Comment by igor-alexandrov** [comment]
@veelenga good to know, that I am not the only one who is confused by how `crystal:` property works. 
In my understanding (on what we had here: https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html) having `crystal: ">= 0.33.0"` means that Crystal should be newer then 0.33 but less then 1.0.0 (ie: >= x.y.z, < (x+1).0.0).

In my original commit I had `crystal: 1.0.0` which in my understanding means `more than 1.0.0, but less than 2.0.0`.

Please correct me if I am wrong.

**Comment by robacarp** [comment]
From that linked doc:

> The semantics of the crystal: property though is slightly different from dependencies’ version: crystal: x.y.z is interpreted as ~> x.y, >= x.y.z (ie: >= x.y.z, < (x+1).0.0) for convenience. The result is that on every major release there will be some maintenance burden.

Which seems like it means you don't need the `< 2.0.0` bit.

**Comment by igor-alexandrov** [comment]
Ok, but I tried to install shards on `awscr-s3` and this is what I got:

```
MacBook-Pro-2:~/workspace/awscr-s3 (master)$ shards install
Resolving dependencies
Fetching https://github.com/taylorfinnell/awscr-signer.git
Fetching https://github.com/crystal-community/timecop.cr.git
Fetching https://github.com/manastech/webmock.cr.git
Unable to satisfy the following requirements:

- `crystal (~> 0.31, >= 0.31.0)` required by `awscr-signer 0.8.1`
- `crystal (>= 0.33.0)` required by `timecop 0.4.1`
- `crystal (>= 0.36.0, < 2.0.0)` required by `webmock 0.14.0+git.commit.42b347cdd64e13193e46167a03593944ae2b3d20`
```

**Comment by robacarp** [comment]
Hm. Doing some quick searching, [It seems like the core team might be having other problems](https://github.com/crystal-lang/shards/pull/493) with the shard command. Is that what this is?

**Comment by veelenga** [comment]
> In my understanding (on what we had here: https://crystal-lang.org/2020/06/09/crystal-0.35.0-released.html) having crystal: ">= 0.33.0" means that Crystal should be newer then 0.33 but less then 1.0.0 (ie: >= x.y.z, < (x+1).0.0).

The doc explains the strict version definition:

> crystal: x.y.z is interpreted as ~> x.y, >= x.y.z (ie: >= x.y.z, < (x+1).0.0) for convenience. 

So, i.e. if that would be `0.33.0`, we would have to change that. But `>= 0.33.0` should work well. 

In any case, i'm ok to merge this as is and would be happy if that solves the problem.

**Comment by veelenga** [comment]
If i point awscr-s3 to your fork, it still throws an error:

```
awscr-s3 git:master ❯ shards update                                                                                                                                                                                                                   ⏎ ✹
Resolving dependencies
Fetching https://github.com/taylorfinnell/awscr-signer.git
Fetching https://github.com/igor-alexandrov/timecop.cr.git
Fetching https://github.com/manastech/webmock.cr.git
Unable to satisfy the following requirements:

- `crystal (~> 0.31, >= 0.31.0)` required by `awscr-signer 0.8.1`
- `crystal (>= 0.33.0, < 2.0.0)` required by `timecop 0.4.1+git.commit.6fb6cd697edeb49e4b5797ee5f9d437cf49ceccd`
- `crystal (>= 0.36.0, < 2.0.0)` required by `webmock 0.14.0+git.commit.42b347cdd64e13193e46167a03593944ae2b3d20`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.

```

So i assume this fix will not help.

**Comment by veelenga** [comment]
I experimented a bit and noticed that the correct way to fix the problem is to release a new version of https://github.com/taylorfinnell/awscr-signer. That's because the awscr-s3 points to awscr-signer v0.8.1, which doesn't have a compatible crystal version (i.e. `crystal: 0.31.0`):

https://github.com/taylorfinnell/awscr-signer/commit/a36705071cd329c353dace344b72147b6a5d903d

**Comment by veelenga** [comment]
@igor-alexandrov this now works for me:

```
awscr-s3 git:master ❯ shards update                                                                                                                                                                            
Resolving dependencies
Fetching https://github.com/taylorfinnell/awscr-signer.git
Fetching https://github.com/crystal-community/timecop.cr.git
Fetching https://github.com/manastech/webmock.cr.git
Installing awscr-signer (0.8.2 at 2e461c9)
Using timecop (0.4.1)
Using webmock (0.14.0 at 42b347c)
Writing shard.lock

```

**Comment by igor-alexandrov** [comment]
@veelenga I've managed to publish new release: https://github.com/jetrockets/shrine.cr/releases/tag/v0.6.2, however for now the only workaround is to use `master` branch of `awscr-s3`:

```
  awscr-s3:
    github: taylorfinnell/awscr-s3
    branch: master
```

Thanks for your help!

**Comment by taylorfinnell** [comment]
@igor-alexandrov I released a new version of `awscr-s3` which I think will also solve your issues. Sorry for the problems

**Pull request closed without merging**
